PyString_FromString -> PyUnicode_FromString
In epgcache.cpp convert to ePyObject() to fix compile error:

../../git/lib/dvb/epgcache.cpp:1520:15: note:   and each type can be converted to the other
| ../../git/lib/dvb/epgcache.cpp:1523:15: error: operands to '?:' have different types 'PyObject*' {aka '_object*'} and 'ePyObject'
|  1523 |     tmp = ptr ? PyUnicode_FromString(ptr->getExtendedDescription().c_str()) : ePyObject();
|       |           ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 72f46fec3b800346a59aa3382e669221ed1c245a)